
services:
  immudb:
    image: codenotary/immudb:latest
    ports:
      - '3322:3322'
    volumes:
      - immudb_data:/var/lib/immudb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - immudb
    environment:
      - IMMUDB_ADDRESS=immudb
      - IMMUDB_PORT=3322
      - IMMUDB_USERNAME=immudb
      - IMMUDB_PASSWORD=immudb
      - IMMUDB_DATABASE=defaultdb
      - GIN_MODE=release
      - PORT=8080
      - IMMUDB_API_KEY=${IMMUDB_API_KEY}
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080

volumes:
  immudb_data:
